// This file is automatically generated. Do not edit it directly.
// IMPORTANT: This client creation is commented out to prevent multiple GoTrueClient instances
// Use the singleton client from @/lib/supabaseClient instead
import type { Database } from './types';

const SUPABASE_URL = "https://hihfygdfoyunyejtkwnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpaGZ5Z2Rmb3l1bnllanRrd25wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDUyODUsImV4cCI6MjA2OTk4MTI4NX0.4dJ7rs2_2OhiBWGlZSkYjWxorgQIb3BbZU91kAIvd4Q";

// IMPORTANT: DO NOT CREATE A CLIENT HERE - Use the singleton from @/lib/supabaseClient
// This prevents "Multiple GoTrueClient instances detected" errors
// 
// Import the supabase client like this:
// import { supabase } from "@/lib/supabaseClient";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });